Uma API protection code for review - Note key store and password code pending, will check with Arnab how to create a key store
JanssenProject/jans-config-api pull request #1
Opened 2020-11-05 15:28 UTC by pujavs

Please find attached excel[
[configapi-review.xlsx](https://github.com/JanssenProject/jans-config-api/files/5495298/configapi-review.xlsx)
](url)

2020-11-05 15:42 UTC, yuriyz requested changes
- Lets remove all commented code which are not in use to keep code clean
- Please use spaces instead of TABs. Otherwise it re-formats all code and it's hard to read and indentify changed places.

Once it's done, please re-open PR.

2020-11-05 15:44 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/UmaAuthorizationService.java
> +		List<String> filteredKeys = keys.stream().filter(k -> k.contains(path)).collect(Collectors.toList());
It seems you refer to keys as paths. Maybe better name it `paths`/`filteredPaths`.

2020-11-05 15:44 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/UmaAuthorizationService.java
> +					Response.status(Response.Status.UNAUTHORIZED).build());
`mataching ` -> `matching `

2020-11-05 15:48 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/UmaAuthorizationService.java
> +			if (result != null && result.length > 0) {
What are you trying to do with `String[] result = key.split(":::");` ? Is it manual parse of json ?
We have jackson which already knows how to parse json into objects. @duttarnab please point @pujavs to `uma-rs` code and jackson parsing. Actually if json format matches it should work 1:1 with `uma-rs` (used by `oxd`/`jans-client-api`).

2020-11-06 10:44 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/UmaAuthorizationService.java
> +		List<String> filteredKeys = keys.stream().filter(k -> k.contains(path)).collect(Collectors.toList());
Renamed to filteredPaths

2020-11-06 10:45 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/UmaAuthorizationService.java
> +					Response.status(Response.Status.UNAUTHORIZED).build());
Done

2020-11-06 10:47 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/UmaAuthorizationService.java
> +			if (result != null && result.length > 0) {
Its not parsing of json 
Reason for this method is mismatch in format of UmaResource name compared to the method and path coming from filter.
Example:UMAResource name = [POST, PUT]:::/api/v1/scopes however coming from filter is simply 
PUT /api/v1/scopes=UmaResource
Note that to avoid creating multiple UMAResources with same detail except http method we are combining the http methods. That is rather than creating two UMAResources as, PUT /api/v1/scopes and POST /api/v1/scopes we are creating one UmaResource as [POST,PUT]:::/api/v1/scopes
Please let me know if there is a better approach than this?

2020-11-06 16:38 UTC, yuriyz approved these changes
@pujavs Merging it but please correct according to comment and make sure UMA Resource is persisted (no in cache only but saved by PersistenceManager). We don't want to create UMA Resource again and again.

2020-11-06 16:38 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/UmaAuthorizationService.java
> +            if (result != null && result.length > 0) {
`result.length > 0` -> `result.length > 1`. In next line you have `result[1]`, so if length is more then 0, e.g. 1 and reference `result[1]`, it will throw IndexOutOfBoundsException.

2020-11-06 16:38 UTC, merged

2020-11-09 07:25 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/UmaAuthorizationService.java
> +            if (result != null && result.length > 0) {
Done

2020-11-09 07:38 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/UmaAuthorizationService.java
> +			if (result != null && result.length > 0) {
@duttarnab  - I had gone through uma-rs code to read the json and load the uma-resource-protection json but for the request coming for individual http-method and the way we store resources in DB we would either  need to create multiple resources or some kind of will workaround like I have done here.    
Please read reason for this method :: is mismatch in format of UmaResource name compared
to the method and path coming from filter
Exmaple UMAResource name = [POST, PUT]:::/api/v1/scopes however coming from
filter is simply PUT /api/v1/scopes=UmaResource
Note that to avoid creating multiple UMAResources with same detail except
http method we are combining the http methods.
That is rather than creating two UMAResources as, PUT /api/v1/scopes and POST
/api/v1/scopes we are creating one UmaResource as [POST,
PUT]:::/api/v1/scopes
Please let me know if there is a better approach than this?
Reference : 
https://github.com/JanssenProject/jans-config-api/blob/master/src/main/resources/uma-rs-protect.json
https://github.com/JanssenProject/jans-config-api/blob/master/src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java

2020-11-09 09:42 UTC, pujavs commented
> @pujavs Merging it but please correct according to comment and make sure UMA Resource is persisted (no in cache only but saved by PersistenceManager). We don't want to create UMA Resource again and again.
@yuriyz,  code to persist the scope and resource already exists  in respective service which is called to create the resource. 
Refer: 
Scope: UmaResourceProtectionService.createScopeIfNeeded() -> scopeService.addScope(scope);
Resource: UmaResourceProtectionService.createResourceIfNeeded() -> umaResourceService.addResource(umaResource);
Do I have to do anything else?
![image](https://user-images.githubusercontent.com/43700552/98524947-d2fdf280-229d-11eb-8ecb-781f11c09d92.png)
------------------------------------------------------------
![image](https://user-images.githubusercontent.com/43700552/98525027-ee68fd80-229d-11eb-8c9e-fe9956eaf2ad.png)

2020-11-09 10:38 UTC, yuriyz commented
If it's saved to persistence and we load it on start up (and put to cache) then it looks good. Thanks.

2020-11-09 11:46 UTC, duttarnab commented on src/main/java/io/jans/configapi/auth/UmaAuthorizationService.java
> +			if (result != null && result.length > 0) {
Hi @pujavs, I understood you have put `http-method` and `path` in the key (separated by `:::`) to store `RsResource` in the cache. I just have an idea to make the code is clean and readable because it is confusing when you split/or create keys at a different place in the code.

Can we create static methods like `createUmaResourceKey (httpMethod, path)`, `getUmaResourceKey` and `public UmaResource readUmaResourceKey( String key)` which will cover the creation/splitting/reading (of path,method) of keys. You can choose your own method names. So we can also reuse these methods whenever required.

2020-11-09 13:06 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/UmaAuthorizationService.java
> +			if (result != null && result.length > 0) {
Thanks @duttarnab  for reviewing the code as discussed the split code is fine and required to get the requested resource from cache.
And your suggestion to make the method static to enable reuse these methods whenever required is good to have.

@yuriyz , whenever you have time request you to please go through the method and let me know if you have any queries.
Reference:
https://github.com/JanssenProject/jans-config-api/blob/master/src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java#L133
https://github.com/JanssenProject/jans-config-api/blob/master/src/main/java/io/jans/configapi/auth/UmaAuthorizationService.java#L68