Jans config api dev
JanssenProject/jans-config-api pull request #18
Opened 2021-02-19 12:54 UTC by pujavs

@yuriyz , request to please review and provide feedback on implementation of Api protection with simple and Jwks bearer token

Details and evidence of enhancement in issue#17
https://github.com/JanssenProject/jans-config-api/issues/17

2021-02-19 13:09 UTC, yuriyz requested changes
Please check inlined comments.

2021-02-19 13:09 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/OpenIdAuthorizationService.java
> +
Code is not formatted. Also, please use spaces instead of tab which works better during reviews.

2021-02-19 13:09 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/OpenIdAuthorizationService.java
> +			Jwt idToken = jwtUtil.parse(acccessToken);
There is already `JwtUtil.isJwt()` method, can it be re-used here?

2021-02-19 13:09 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/OpenIdAuthorizationService.java
> +			log.error("oAuth Invalid Jwt "+token);
If it's JWT and we got exception, then we failed to validate it and thus error should be returned directly from here.

2021-02-19 13:09 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/util/JwtUtil.java
> +			}
"EC" is missed.

2021-02-19 13:09 UTC, yuriyz commented on src/main/java/io/jans/configapi/configuration/ConfigurationFactory.java
> +    private void addSecurityProviders() {
Is there dependency on jans-auth-server model? In this case you wouldn't need this copy-paste and can re-use `SecurityProviderUtility`

https://github.com/JanssenProject/jans-auth-server/blob/f6a912733c35bd5437f445758abba7e78b4dba9a/model/src/main/java/io/jans/as/model/util/SecurityProviderUtility.java#L36

2021-02-19 13:09 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/util/JwtUtil.java
> +		log.trace("\n\n JwtUtil::isJwt()  token = " + token);
tabs->spaces

2021-02-19 13:09 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/client/AuthClientFactory.java
> +
tabs->spaces

2021-02-22 07:03 UTC, pujavs commented on pom.xml
> +            <scope>runtime</scope>
Done

2021-02-22 07:12 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/OpenIdAuthorizationService.java
> +
Sorry for repeating the same issues, always forget to set the space when i create a new workspace.
 Have formatted all the code now

2021-02-22 07:19 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/OpenIdAuthorizationService.java
> +			Jwt idToken = jwtUtil.parse(acccessToken);
Right and I had created the same to use it here but missed ... 
Done the change now

2021-02-22 07:19 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/OpenIdAuthorizationService.java
> +			log.error("oAuth Invalid Jwt "+token);
Agreed, changes done.

2021-02-23 12:53 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/util/JwtUtil.java
> +			}
Implemented EC and tested both EC as well as RSA.

2021-02-23 13:19 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/util/JwtUtil.java
> +		log.trace("\n\n JwtUtil::isJwt()  token = " + token);
formatted from tabs to 4 spaces

2021-02-23 13:19 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/client/AuthClientFactory.java
> +
formatted from tabs to 4 spaces

2021-02-26 17:06 UTC, pujavs commented
@yuriyz, did you get a chance to review the change? If the changes are good request you to please approve and merge with master.

2021-02-26 17:24 UTC, yuriyz approved these changes

2021-02-26 17:25 UTC, merged