Configapi uma and openId protect code
JanssenProject/jans-config-api pull request #2
Opened 2020-11-17 17:27 UTC by pujavs

@yuriyz Request you to please review the code.
- Based on discussion and suggestion from @duttarnab had changed the code from using keystore to using clientId-clientSecret to generate PAT.
- To test the code i had gnerated the token using the oxTrust curl 
curl -k -u '<clientId:clientSecret>' https://pujavs.gluu42.server/oxauth/restv1/token -d grant_type=client_credentials
- However for both OpenId and UMA I am getting "401 Unauthorized" error. Will talk to @duttarnab tomorrow.
- Attached are logs for your reference. 

[oxauth_UMA_API_Protection_17Nov2020_3.logs.pdf](https://github.com/JanssenProject/jans-config-api/files/5555112/oxauth_UMA_API_Protection_17Nov2020_3.logs.pdf)

[oxauth_OPENID_api_protection_17Nov2020_4.logs.pdf](https://github.com/JanssenProject/jans-config-api/files/5555116/oxauth_OPENID_api_protection_17Nov2020_4.logs.pdf)

2020-11-17 18:09 UTC, yuriyz requested changes
There many copy-pastes from `uma-rs`, we should re-use code.

2020-11-17 18:09 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java
> +    // Is this fine?
We should operate with name. Name is saved under `oxId` attribute of the `Scope` OC.

https://github.com/GluuFederation/oxAuth/blob/fd05fd5ee94cb5553583fadb009a3ecfd1c795bc/persistence-model/src/main/java/org/oxauth/persistence/model/Scope.java#L34

2020-11-17 18:09 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java
> +                scopes.add(scope.getInum() + "," + scope.getDn());
I'm not sure what would that means "inum + dn", if DN is already there then what is the sense to add inum to dn ?

Reverse this logic to work based on scope names (not inum or dn). I you fetch resource from persistence, it references DN, so load scope and take name of it (`oxId`).

2020-11-17 18:09 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/client/OpenIdClientService.java
> +@ApplicationScoped
Why do we need duplicate already defined interface from jans-auth-client ? 

We have it here:
https://github.com/JanssenProject/jans-auth-server/blob/56dbfd807233e509a824b23122489d6c266fcce7/client/src/main/java/io/jans/as/client/service/IntrospectionService.java#L22

Is it because quarkus refuse to work with it ? If yes, can you post exact exception or describe problem ?

2020-11-17 18:09 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/client/UMATokenService.java
> +    Response requestAccessToken(
This is covered by `TokenClient`.

https://github.com/GluuFederation/oxAuth/blob/647bc865d7f121e3da4ab360a59b4b7ed6fd456c/Client/src/main/java/org/gluu/oxauth/client/TokenClient.java#L22

2020-11-17 18:09 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/model/Condition.java
> +public class Condition {
It's copy-paste from `uma-rs` project. Please add dependency and use library/dependency.

2020-11-18 07:43 UTC, pujavs commented
> There many copy-pastes from `uma-rs`, we should re-use code.
uma-rs could not be reused due to resteasy dependency conflict with Quarkus. Remember earlier when using auth-client also we were getting the conflicts and we decided to code clients within config-api itself.
For reference here are the issues of few conflicts - [Quarkus_Issue_Resolution.txt.pdf](https://github.com/JanssenProject/jans-config-api/files/5558495/Quarkus_Issue_Resolution.txt.pdf)

2020-11-18 07:53 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/client/OpenIdClientService.java
> +@ApplicationScoped
Yes due to resteasy dependency conflict with Quarkus. 
For reference here are the issues of few conflicts - Quarkus_Issue_Resolution.txt.pdf

2020-11-18 07:56 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java
> +                scopes.add(scope.getInum() + "," + scope.getDn());
Like i mentioned in the comments i appended the "inum + dn" by looking at the sample scopes in Gluu schema, thinking that I was doing the right thing keeping it in sync with other gluu code.
However will now rework the logic based on name.

2020-11-18 07:59 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/client/UMATokenService.java
> +    Response requestAccessToken(
Reason is same that is due to resteasy dependency conflict with Quarkus.  The PAT generation code worked by adding this restclient

2020-11-18 08:01 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/model/Condition.java
> +public class Condition {
I know its copy paste but the uma-rs code was not working due to resteasy conflict and i thought rather than adding the dependency for only these 3 class i would rathermove them within config-api. 
However will add the dependency for these 3 classes if you say so...

2020-11-18 09:27 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java
> +                scopes.add(scope.getInum() + "," + scope.getDn());
DN = `inum=` + inum + baseDN. While here you seems to get already constructed dn. Even if you tried to construct it it's not correct due to missed `inum=`. Anyway, lets make it via names.

2020-11-18 09:32 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/client/OpenIdClientService.java
> +@ApplicationScoped
Nice report. It seems it's not easy to get quarkus work with jans-auth-client . Understood.

2020-11-18 09:33 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/client/UMATokenService.java
> +    Response requestAccessToken(
Clear.

2020-11-18 09:33 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/model/Condition.java
> +public class Condition {
Yes, please. Because we may add or remove something in future and then it would lead to redundant work in future.

2020-11-18 09:35 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java
> +                                                                                                    // To be reviewed by
Done

2020-11-18 10:13 UTC, yuriyz commented
All these problems makes me think that we should move away from Quarkus in `jans-config-api` (or otherwise move `jans-auth-server` to Quarkus). cc @nynymike

2020-11-18 13:18 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java
> +    // Is this fine?
Done

2020-11-18 13:20 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java
> +                scopes.add(scope.getInum() + "," + scope.getDn());
Changes done.

2020-11-18 13:20 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/model/Condition.java
> +public class Condition {
Changes done, now using model classes directly from  jans-client-api

2020-11-18 14:29 UTC, yuriyz requested changes

2020-11-18 14:29 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java
> +            scopes.add(strScope);
It's not clear why do we need this method. We have list of scopes and returns same list of scopes. If you remove this method it shouldn't effect anything, right?

2020-11-18 15:32 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java
> +            scopes.add(strScope);
Correct, its not required any more and hence removed the same.

2020-12-09 18:55 UTC, pujavs commented
@yuriyz , I modified jans-config code for oauth scope as discussed and have also updated swagger api doc for appropriate scope. 
Request review and merge with master if appraopraite.

**Note**: Have tested oauth for auth properties resource. Attached are the test report and jans-auth-server logs
1) Karate Test Report for properties
[src.test.resources.feature.config.properties.properties.pdf](https://github.com/JanssenProject/jans-config-api/files/5668042/src.test.resources.feature.config.properties.properties.pdf)

2) local jans-auth-server logs
[jans-auth_9Dec2020_OAuth_Final_Working.log](https://github.com/JanssenProject/jans-config-api/files/5668065/jans-auth_9Dec2020_OAuth_Final_Working.log)

2020-12-10 09:10 UTC, yuriyz approved these changes

2020-12-10 09:10 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/service/UmaService.java
> +            log.debug("RPT status response: {} "+ rptStatusResponse);
Duplicate entries, remove it.

2020-12-10 09:10 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/service/UmaService.java
> +                    boolean hasResourcePermission = this.hasResourcePermission(rptStatusResponse, resourceId);
Now it looks correct.

2020-12-10 09:11 UTC, merged

2020-12-10 09:14 UTC, yuriyz commented
It's working state but requires improvements in many places. This will be improved in separate PRs by @pujavs