Configapi uma protect
JanssenProject/jans-config-api pull request #3
Opened 2020-12-18 07:41 UTC by pujavs

@yuriyz ,
I have refactored code, tested the oauth2 flow and cleaned up the code for as well as improved  logging.
Request you to please review.

2020-12-18 09:11 UTC, yuriyz requested changes
We shouldn't put test code in application source code. It has to be in test sources. Also use suite setup and tear down.

2020-12-18 09:11 UTC, yuriyz commented on src/main/java/io/jans/configapi/filters/AuthorizationFilter.java
> +    ApiTestMode apiTestMode;
We can't use test code in production. Test code should live within tests only. Refactor it to traditional setUp/tearDown.
For this particular case it should be on suite level. So we pick up what we need one time before whole suite and then tear it down when it finishes.

2020-12-18 09:11 UTC, yuriyz commented on src/main/java/io/jans/configapi/filters/AuthorizationFilter.java
> +        finally {
It must be in tearDown of the suite. In junit.jupiter I guess it's `@AfterAll`, no ?

2020-12-18 09:11 UTC, yuriyz commented on src/main/java/io/jans/configapi/filters/AuthorizationFilter.java
> +    private String testAuthenticationPrep(ResourceInfo resourceInfo, String method, String path) throws Exception {
Must be in test sources as well as ApiTestMode.

2020-12-18 09:11 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java
> +                     */
Remove commented code.

2020-12-18 09:11 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/client/AuthClientFactory.java
> +         //       .post(Entity.form(new MultivaluedHashMap<String, String>(tokenRequest.getParameters())));
Remove redundant commented lines.

2020-12-18 09:11 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/client/AuthClientFactory.java
> +         //       .post(Entity.form(new MultivaluedHashMap<String, String>(tokenRequest.getParameters())));
Redundant lines.

2020-12-18 09:11 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/service/UmaService.java
> +            log.warn("Token is blank");
trace

2020-12-18 09:11 UTC, yuriyz commented on src/main/java/io/jans/configapi/auth/util/ApiTestMode.java
> +public class ApiTestMode {
Test code must be in test sources.

2021-01-06 12:36 UTC, pujavs commented on src/main/java/io/jans/configapi/filters/AuthorizationFilter.java
> +    ApiTestMode apiTestMode;
Modified the code to move the test code within test folder.
jans-config-api uses Quarkus and Karate framework making it complex and no proper hooks to implement.
If only Quarkus was used and also test cases were written as QaurkusTest  we could have used the QuarkusTestCallbacks like QuarkusTestBeforeAllCallback, QuarkusTestBeforeEachCallback,QuarkusTestAfterEachCallback OR Junit Test then we could have used the setup/tearDown with either Junit @BeforeAll, @AfterAll, @BeforeEach.
But at present we have one single Test class KarateTestRunner/JenkinsTestRunner and this is called only once thus token generation for each feature test scenario method is not possible.
So after much exploration i could come up with Karate hooks
**Our requirement:** 
1) We need test client 
2) Appropriate token for each scenario method that
**Implementations:**
1) Before execution of Karate feature create client :- During Karate config setup the client is created. This is implemented in karate-config.js for local and karate-config-jenkins.js using testClient.feature for jenkins. Status local is tested, jenkins that is via karate-config-jenkins.js is pending
2) accessToken generation and passing in header :- Required before invoking each endpoint method. Code in each feature file calling token.feature to generate accessToken. Status tested locally for three features attributes.feature, cache.feature and clients.feature. Jenkins env is pending. 
Once you approve the change plan is to enable the same for all features.

2021-01-06 12:37 UTC, pujavs commented on src/main/java/io/jans/configapi/filters/AuthorizationFilter.java
> +        finally {
Removed the same.

2021-01-06 12:39 UTC, pujavs commented on src/main/java/io/jans/configapi/filters/AuthorizationFilter.java
> +    private String testAuthenticationPrep(ResourceInfo resourceInfo, String method, String path) throws Exception {
Moved the test code from main java code AuthorizationFilter class to test src code.

2021-01-06 12:39 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/UmaResourceProtectionService.java
> +                     */
Removed commented code

2021-01-06 12:40 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/client/AuthClientFactory.java
> +         //       .post(Entity.form(new MultivaluedHashMap<String, String>(tokenRequest.getParameters())));
Removed commented code

2021-01-06 12:40 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/client/AuthClientFactory.java
> +         //       .post(Entity.form(new MultivaluedHashMap<String, String>(tokenRequest.getParameters())));
Removed the redundant code

2021-01-06 12:40 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/service/UmaService.java
> +            log.warn("Token is blank");
changed to trace

2021-01-06 12:41 UTC, pujavs commented on src/main/java/io/jans/configapi/auth/util/ApiTestMode.java
> +public class ApiTestMode {
Agreed, have moved the test code to test src

2021-01-14 05:08 UTC, pujavs commented
@yuriyz , request you to please review and share feedback. If you are find with the changes then request approve of merge request

2021-01-14 17:37 UTC, yuriyz approved these changes

2021-01-14 17:37 UTC, merged