Jans config api 33
JanssenProject/jans-config-api pull request #34
Opened 2021-05-14 16:07 UTC by pujavs

@yuriyz , request you to please review the changes for - Move project to Weld and remove Quarkus dependency
https://github.com/JanssenProject/jans-config-api/issues/33
1) I have removed all dependency to Quarkus 
2) Used Weld CDI 
3) Removed redundant code
4) Restructured the code

Note: Regarding merge to master i think we should wait for setup changes. Will request @mbaser if he can help in the same.

2021-05-14 18:01 UTC, yuriyz requested changes
Please check inlined comments.

2021-05-14 18:01 UTC, yuriyz commented on server/src/test/resources/feature/config/cache/cache.feature
> +    And header Content-Type = 'application/json'
Why is content type changed ? According to json patch content type has to be `application/json-patch+json`, no ?

2021-05-17 06:24 UTC, pujavs commented on common/src/main/java/io/jans/configapi/exception/GlobalErrorHandler.java
> +        log.error(" ******** GlobalErrorHandler ************ " + e.getMessage(), e);
Right, removed  the redundant log

2021-05-17 06:25 UTC, pujavs commented on server/src/main/java/io/jans/configapi/configuration/AppInitializer.java
> +    // void onStart(@Observes @Initialized(ApplicationScoped.class) Object init) {
Done

2021-05-17 06:26 UTC, pujavs commented on server/src/main/java/io/jans/configapi/configuration/CustomConfigSource.java
> +            e.printStackTrace();
Done

2021-05-17 06:27 UTC, pujavs commented on server/src/main/java/io/jans/configapi/configuration/CustomConfigSource.java
> +    private final String FILE_CONFIG = "application.properties";
Done

2021-05-17 06:33 UTC, pujavs commented on server/src/main/java/io/jans/configapi/configuration/CustomConfigSource.java
> +            Properties properties = this.readPropertiesFile(FILE_CONFIG);
Agreed, rectified the code

2021-05-17 06:34 UTC, pujavs commented on server/src/main/java/io/jans/configapi/configuration/CustomConfigSource.java
> +            e.printStackTrace();
Done

2021-05-17 06:38 UTC, pujavs commented on server/src/main/java/io/jans/configapi/security/service/AuthClientService.java
> +    /*
Done

2021-05-17 06:40 UTC, pujavs commented on server/src/main/java/io/jans/configapi/util/AuthUtil.java
> +    /*
Done

2021-05-17 07:41 UTC, pujavs commented on server/src/test/resources/feature/config/cache/cache.feature
> +    And header Content-Type = 'application/json'
Because was getting 415 - Unsupported Media Type error and changing the resteasy version the dependency error fpr auth-client error. Rechecking if i can find a solution

**415 Error**
 status code was: 415, expected: 200, response time: 229, url: http://localhost:8080/jans-config-api/api/v1/attributes/6609, response:
attributes.feature:178 - status code was: 415, expected: 200, response time: 229, url: http://localhost:8080/jans-config-api/api/v1/attributes/6609, response: 
![image](https://user-images.githubusercontent.com/43700552/118449216-8e518900-b710-11eb-8b36-a4b22dcdc2f9.png)

2021-05-17 09:18 UTC, yuriyz commented on server/src/test/resources/feature/config/cache/cache.feature
> +    And header Content-Type = 'application/json'
Please double check you have `application/json-patch+json` on resource class which serve request. It throws unsupported media type if it's not served on server. But it's bug, we have to serve it.

2021-05-18 13:15 UTC, pujavs commented on server/src/main/java/io/jans/configapi/configuration/CustomConfigSource.java
> +            Properties properties = this.readPropertiesFile(FILE_CONFIG);
Removed redundant load

2021-06-29 11:06 UTC, pujavs commented on server/src/test/resources/feature/config/cache/cache.feature
> +    And header Content-Type = 'application/json'
Json patch **does not work with resteasy version 3.14.0.Final**, for Json patch to work we need resteasy version 4.5.6.Final

### Analysed approaches:
1) If using resteasy dependency version same as jans-auth-server then using Json patch with MediaType.APPLICATION_JSON_PATCH_JSON -> “application/json-patch+json gives 415 - Unsupported Media Type error
2) If we exclude resteasy (3.14.0.Final)  from jans dependency and use the latest resteasy version(4.5.6.Final)  than we will have to write the jans auth client again like in Quarkus
3) Upgrade resteasy versions in all jans-auth and other jans-client to latest, 4.5.6.Final or above

### Final  Implementation:
Approach#2 from above -> Upgraded resteasy version 4.5.6.Final in jans-config-api. Since 4.5.6.Final is not compatible with existing jans-auth and jans-client hence created the resteasy client for introspection in jans-config-api. This is same as used in Quarkus.

2021-06-29 11:09 UTC, pujavs reviewed
@yuriyz , request you to please review the changes for - Move project to Weld and remove Quarkus dependency. I have upgraded the resteasy version to 4.5.6.Final to make Json Patch work.
#33
**Note:** Regarding merge to master i think we should wait for setup changes. Once your verify and confirm that the changes are fine. I will request @mbaser for jans-setup modification.

2021-06-29 12:02 UTC, yuriyz approved these changes

2021-06-29 12:02 UTC, merged