Issue 59
JanssenProject/jans-config-api pull request #61
Opened 2021-09-01 15:11 UTC by pujavs

Change to enable oauth2 validation based on config attribute configOauthEnabled

Related change request -> https://github.com/JanssenProject/jans-config-api/issues/59

2021-09-01 15:31 UTC, yuriyz requested changes

2021-09-01 15:31 UTC, yuriyz commented on server/src/main/java/io/jans/configapi/filters/AuthorizationFilter.java
> +        if (configOauthEnabled) {
Please use "early exit" approach to avoid nested ifs.
```
if (!configOauthEnabled) {
    log.info("Authorization granted.");
}
```

2021-09-01 15:33 UTC, yuriyz commented
@ossdhaval can you check why sonar didn't check this PR ? I don't see on checks above.

2021-09-01 15:34 UTC, yuriyz commented
@pujavs please fix `Code quality check`.

2021-09-01 15:57 UTC, pujavs commented on server/src/main/java/io/jans/configapi/filters/AuthorizationFilter.java
> +        if (configOauthEnabled) {
Done

2021-09-02 09:27 UTC, pujavs commented
> @pujavs please fix `Code quality check`.

Tried to fix the sonar pom changes not fixed code smells
![image](https://user-images.githubusercontent.com/43700552/131819427-e8b06879-0945-4e79-9457-64ce6d42a8aa.png)

2021-09-02 15:47 UTC, yuriyz commented
Merging. I think sonar is mis-configured. It does not show statistic for this PR but for whole project.

You can see all code smells here https://sonarcloud.io/project/issues?id=JanssenProject_jans-config-api&open=AXuls1jbZRsyWtZ_ABfd&pullRequest=61&resolved=false&types=CODE_SMELL

2021-09-02 15:47 UTC, yuriyz approved these changes

2021-09-02 15:47 UTC, merged

2021-09-03 02:15 UTC, ossdhaval commented
> @ossdhaval can you check why sonar didn't check this PR ? I don't see on checks above.

Checking. In the meanwhile, a perspective shared [here](https://community.sonarsource.com/t/show-only-new-issues-in-changed-files/11423/2)

2021-09-03 02:16 UTC, ossdhaval commented
> @ossdhaval shouldn't sonar show checks for this PR only ? It seems to show checks for whole project. See above.

Checking. In the meanwhile, a perspective shared [here](https://community.sonarsource.com/t/show-only-new-issues-in-changed-files/11423/2)

2021-09-03 07:07 UTC, ossdhaval commented
Observation: It is not reporting for whole project but showing all bugs for files that have been changed. Not just the changed lines. Surprisingly, it is showing bugs reported on those files 2 months back, while our new code definition is 30 days. 
One reason could be that PR was raised before we set the `new code` definition. I am checking what is the behaviour for other recent PRs.

2021-09-03 08:50 UTC, yuriyz commented
@ossdhaval It seems you are right, it's scan of modified files. Thanks for info.