feat: client pagination enhancement
JanssenProject/jans-config-api pull request #87
Opened 2021-11-03 17:03 UTC by pujavs

Hello @yuriyz, the change is to enable pagination for openid client request.

Client ticket ref: https://support.gluu.org/other/10067/clients-paging/

2021-11-03 17:19 UTC, yuriyz requested changes
See inlined comments.

2021-11-03 17:19 UTC, yuriyz commented on common/src/main/java/io/jans/configapi/util/ApiConstants.java
> +    public static final String DEFAULT_LIST_START_INDEX = "1";
Size and index has to be `int`, not `String`.

2021-11-03 17:19 UTC, yuriyz commented on server/src/main/java/io/jans/configapi/rest/resource/auth/BaseResource.java
> +        if (StringUtils.isNotEmpty(schemas)) {
As in previos PRs, when we make "early exit" we don't have all these block nestings.
```
if (StringUtils.isEmpty(schemas)) {
    return Response.status(Response.Status.BAD_REQUEST).entity("Schema(s) not supplied in Search Request")
                    .build();    
}
```

2021-11-03 17:19 UTC, yuriyz commented on server/src/main/java/io/jans/configapi/rest/resource/auth/BaseResource.java
> +            if (count <= getMaxCount()) {
```
if (count > getMaxCountLimit())  {
     return Response.status(Response.Status.BAD_REQUEST)
                        .entity("Maximum number of results per page is " + getMaxCount()).build();
}

```

2021-11-03 17:19 UTC, yuriyz commented on server/src/main/java/io/jans/configapi/rest/resource/auth/ClientsResource.java
> +        SearchRequest searchReq = new SearchRequest();
`SearchRequest searchReq = createSearchRequest(...)`

2021-11-04 08:39 UTC, pujavs commented on common/src/main/java/io/jans/configapi/model/configuration/ApiAppConfiguration.java
> +    private int maxCount;
It is configuration max count which will be read from DB.

2021-11-04 12:01 UTC, pujavs commented on common/src/main/java/io/jans/configapi/util/ApiConstants.java
> +    public static final String DEFAULT_LIST_START_INDEX = "1";
These are used a javax.ws.rs.DefaultValue which takes value as String.

2021-11-04 12:03 UTC, pujavs commented on server/src/main/java/io/jans/configapi/rest/resource/auth/BaseResource.java
> +                request.setMaxCount(getMaxCount());
request variable is passed as reference value to the methods and hence the values set inside this method is available to the caller

2021-11-04 12:05 UTC, pujavs commented on server/src/main/java/io/jans/configapi/rest/resource/auth/BaseResource.java
> +    protected Response prepareSearchRequest(String schemas, String filter, String sortBy, String sortOrder,
Refactored the method

2021-11-04 12:05 UTC, pujavs commented on server/src/main/java/io/jans/configapi/rest/resource/auth/BaseResource.java
> +            if (count <= getMaxCount()) {
Done

2021-11-04 12:05 UTC, pujavs commented on server/src/main/java/io/jans/configapi/rest/resource/auth/ClientsResource.java
> +        SearchRequest searchReq = new SearchRequest();
Was not possible with original code as prepareSearchRequest was returning Response but now with refactored code changing as suggested

2021-11-04 12:59 UTC, pujavs commented on server/src/main/java/io/jans/configapi/rest/resource/auth/BaseResource.java
> +        if (StringUtils.isNotEmpty(schemas)) {
Done

2021-11-04 13:00 UTC, pujavs commented on server/src/main/java/io/jans/configapi/rest/resource/auth/BaseResource.java
> +        Response response = null;
not required, removed

2021-11-04 13:39 UTC, pujavs commented on server/src/main/java/io/jans/configapi/rest/resource/auth/ClientsResource.java
> +        if (pagedResult != null) {
Done

2021-11-04 16:27 UTC, yuriyz approved these changes

2021-11-04 16:27 UTC, merged